### ISSUE TITLE
MenuItem should not use custom property name icon

### ISSUE THREAD

**Issue by dano6** [milikhin/seabass2#115]
**Describe the bug**
https://github.com/ubports/qqc2-suru-style/pull/56 will broke app, because property name icon here: https://github.com/milikhin/seabass2/blob/master/ubports-seabass/qml/components/common/MenuItem.qml
It can help with https://github.com/milikhin/seabass2/issues/76 , we could replace `Ubuntu.Components` on another place because `MenuItem` will support icons.

**To Reproduce**
1. Install MR with `sudo ubports-qa install PR_qqc2-suru-style_56`
2. Launch the app
3. It will crash

**Expected behavior**
Nothing will crash ever

**Comment by milikhin** [comment]
Thank you for the report!
I'll rename the property for the next release.
