### ISSUE TITLE
Support for installing and running built apps

### ISSUE THREAD

**Issue by kugiigi** [milikhin/seabass2#119]
**Is your feature request related to a problem? Please describe.**
Building an app just creates a click package. You would need UTTT or File Manager + OpenStore to actually install and run the app.

**Describe the solution you'd like**
An option to deploy the app - install and run built app.

**Describe alternatives you've considered**
Mentioned on first item.

I would greatly appreciate this feature because I'm in a situation where I can't use my development PC for the time being and I want to start a project that I want to use ASAP. I'd be glad to be the first ever to create an app solely via Seabass 😁

**Comment by milikhin** [comment]
Thank you! I'll have a look this weekend. Not sure about starting the app, but the installation seems to be a pretty straightforward task to implement :)

>  I'd be glad to be the first ever to create an app solely via Seabass
Wow, that would be a great test for Seabass! :-)

**Comment by kugiigi** [comment]
Here's a script I used when I was still developing my apps on my Nexus 5 via x forwarding. It may not be dynamic enough and I'm not expert with scripts but it worked quite well when I used it. Hopefully, it'll be a bit of help 😄
[qt_run.txt](https://github.com/milikhin/seabass2/files/6642199/qt_run.txt)

**Comment by milikhin** [comment]
Thank you, that's very helpful!
Could you please try the build to see if it works.
I've added a new button to build + install + launch app.

[seabass2.mikhael_1.1.0_all.click.zip](https://github.com/milikhin/seabass2/files/6642830/seabass2.mikhael_1.1.0_all.click.zip)

**Comment by kugiigi** [comment]
It works well, awesome!
Thanks for working realy fast on this.
Now, I'll be logging more of my requests 😆
