### ISSUE TITLE
Save and restore tabs

### ISSUE THREAD

**Issue by kugiigi** [milikhin/seabass2#122]
**Is your feature request related to a problem? Please describe.**
Currently, you'll have to open each file you want to edit every time you open the app. This isn't ideal when you are working on a project with many files.

**Describe the solution you'd like**
Open tabs will be automatically saved when app is closed and restore when opening. Perhaps this can be optional.

**Describe alternatives you've considered**
An alterative is having some sort of a project definition similar to geany but of course this is a lot more harder 😆

**Comment by milikhin** [comment]
Could you please try the build to see if it works: 
[seabass2.mikhael_1.2.0_all.click.zip](https://github.com/milikhin/seabass2/files/6795409/seabass2.mikhael_1.2.0_all.click.zip)


Tabs restore at startup is enabled by default, but can be disabled in Settings.
The build should also support syntax highlighting for `.mjs` files (#128)

**Comment by kugiigi** [comment]
Both things worked well. Thank you very much!
I'll be able to use and release my app very soon thanks to Seabass :grinning:

**Comment by milikhin** [comment]
Great! Thank you for testing!
