### ISSUE TITLE
Add option to change indention

### ISSUE THREAD

**Issue by kugiigi** [milikhin/seabass2#129]
**Is your feature request related to a problem? Please describe.**
I use 4 spaces in all my projects and the current indention is set to 2 spaces.

**Describe the solution you'd like**
A simple option in the settings page to set it to the number of spaces and perhaps set to tab too.

**Describe alternatives you've considered**
Pressing tab twice :grin

**Additional context**
I think I'm basically looking for Geany features now XD

**Comment by milikhin** [comment]
Seabass supports reading indentation preferences from [.editorconfig](https://editorconfig.org/) files. It's possible to setup indentation independently for different file types. As a simple example to set indent size to 4 spaces for all files something like this should work:
```
[**]
indent_style = space
indent_size = 4
```

**Comment by milikhin** [comment]
By the way I think there is a plugin for Geany to add support for .editorconfig files too :-)

**Comment by kugiigi** [comment]
Awesome, that worked! Thanks!
