### ISSUE TITLE
No way to access settings.

### ISSUE THREAD

**Issue by giiba** [milikhin/seabass2#13]
Maybe I am missing something, but I see no way to access settings to try the dark mode.

In seabass1 the hamburger menu opens with 'settings', 'about', and 'help' and there is an icon to open the file browser on the right of the top bar. In seabass2 the hamburger opens the file browser, and there is no corresponding icon to the right for the other items.

**Comment by milikhin** [comment]
There is no Settings page yet for Seabas2.
For now the only way to activate the dark mode to set the Suru dark theme globally (using UT Tweak Tool for example)

**Comment by milikhin** [comment]
TODO: make these preferences available:

- [ ] print margin
- [ ] font size
- [ ] optionalize soft tabs
- [ ] default soft tab size

**Comment by esklarski** [comment]
Toggling light/dark/system theme would be a nice setting to have too.

**Comment by milikhin** [comment]
> Toggling light/dark/system theme would be a nice setting to have too.

Thank you for the idea!
Toggling theme manually is, I believe, impossible within a pure QML application.
I don't want to add C++ until there are critical blockers for using pure QML.

So we probably won't have the feature for now

**Comment by milikhin** [comment]
Seabass can now read indentation preferences from .editorconfig files
