### ISSUE TITLE
Remember and display last project location when opening Seabass2

### ISSUE THREAD

**Issue by mattbel10** [milikhin/seabass2#136]
**Feature request**
In present app Settings there is an option to restore session at startup. It works great in regard to restore last open tabs in the previous session and I assumed it also remembered and displayed the project location as well, but unfortunately it doesn't and every time I reopen again Seabass2 app, I have to surf myself to my project location.

**Description of the solution I'd like**
I'd wish whenever the "Restore session at startup" is enabled, the last project location would be restored, as well as the last open files.

**Comment by milikhin** [comment]
> I'd wish whenever the "Restore session at startup" is enabled, the last project location would be restored

I think that sounds good as a feature for the next release :-)
