### ISSUE TITLE
Git version 2.7.4 is old

### ISSUE THREAD

**Issue by mattbel10** [milikhin/seabass2#138]
**Is your feature request related to a problem? Please describe**
Git 2.7.4 version downloaded and installed into the Seabass2 Libertine container is old and doesn't have very latest feature: for instance `restore` attribute is missing.

**Describe the solution you'd like**
If this isn't due to the old Ubuntu 16.04 container, I think it would be worth to update it.

**Comment by milikhin** [comment]
Thank you for the request!

The git is installed from Ubuntu repositories. So I think we'll just wait for an update to 20.04 base, and the issue will be fixed automatically :-)

For now though you can install git manually using the "Git stable releases" PPA (https://launchpad.net/~git-core/+archive/ubuntu/ppa) for example. It is possible to access root shell for the Seabass container using `libertine-container-manager exec -i seabass2-build -c bash` or to manage the container using System Settings UI.

**Comment by mattbel10** [comment]
Thank you! Will try your suggestion to update git inside the container.
