### ISSUE TITLE
Register seabass to content-hub

### ISSUE THREAD

**Issue by lduboeuf** [milikhin/seabass2#15]
Thanks for publishing that great app :)

Use case:
I'm in the file explorer app, i  choose a file to view or edit, i choose "open with external application", and don't see Seabass there.
Would be great to have

**Comment by milikhin** [comment]
> Thanks for publishing that great app :)
Thank you!

There seems to be an interesting issue with Content Hub integration.

Use case:
1. I'd like to edit a file
2. I choose a file to edit using File explorer
3. I choose "open with external application" and then choose Seabass

What I expect to happen without knowledge of how content hub works is that the chosen file is opened using Seabass and is available for edit. So when I save the file later -- **the original file is modified**.

But that's not how content hub usually works: instead it creates a copy of the chosen file in the chosen application's (the Seabass') directory. So when a user works with the file opened using Content Hub, **the copy of chosen file is modified** (and not the chosen file itself).

That just need to be taken into consideration when working on the issue.

**Comment by lduboeuf** [comment]
Oh yes you're right, forgot about it. That seems not a viable solution then or only provide a read-only file view.

**Comment by milikhin** [comment]
blocked by #54
