### ISSUE TITLE
Unable to create project

### ISSUE THREAD

**Issue by jhay06** [milikhin/seabass2#175]
![screenshot20240211_234909198](https://github.com/milikhin/seabass2/assets/5191437/74d1c312-3193-4fc0-ade2-6d61bbeb12b6)
always fail and end up on the image above

**Comment by milikhin** [comment]
Seabass requires working Libertine to create/build projects.
It seems from the error message that Libertine crashes with segfault.

Does Libertine work on your device outside of the Seabass?
https://docs.ubports.com/en/latest/userguide/dailyuse/libertine.html
