### ISSUE TITLE
colors in displayed files not themed

### ISSUE THREAD

**Issue by Danfro** [milikhin/seabass2#18]
The theme currently is only applied to the qml part of the app. This leaving index.html not themed = always white background and black text.

From comments on this [MR](https://gitlab.com/ubports/apps/notes-app/-/merge_requests/41/diffs) to notes app I know that html files can be themed too.

From how I understand it, you add color placeholders to the html file like this

```
<style>
    body {
        font-size: 14px;
        font-family: Ubuntu;
        background-color: BACKGROUND_COLOR;
        color: TEXT_COLOR;
    }
</style>
```
and replace them on loading with the appropriate color values maybe like this

`.replace("BACKGROUND_COLOR", theme.palette.normal.background).replace("TEXT_COLOR", theme.palette.normal.foreground)`

But I have to admit I do not know enough of your app to find the right place for that right now. You may know it right away.

**Comment by Danfro** [comment]
Actually, once this works, you might as well try to autoinsert the apps version number the same way.

With your app using MainView, you can pull the apps version number like this:
[weather app AboutPage](https://gitlab.com/ubports/apps/weather-app/-/blob/master/app/components/About.qml#L81)

**Comment by milikhin** [comment]
Thank you very much for the examples!
[loadTheme](https://github.com/milikhin/seabass2/blob/master/ubports-seabass/qml/generic/EditorApi.qml#L98) seems to be a good place to set colors. The idea then is to provide colors with something like this:
```
postMessage('setPreferences', {
       isDarkTheme: isDarkTheme,
       backgroundColor: theme.palette.normal.background,
       textColor: theme.palette.normal.backgroundText
})
```

and then set appropriate colors using JS inside the webview
