### ISSUE TITLE
Navigating left/right and backspace buttons regularly make two steps

### ISSUE THREAD

**Issue by Pohli** [milikhin/seabass2#30]
If I got a text file with many space characters between words navigating in the spaces area regularly takes two steps on one tap, same with backspace. Is this intended? Maybe Seabass falsely (plain text file, no code) detects syntax and activates this "feature"? Or just a general bug?

Jolla Phone with SFOS 3.0.1.11 and Seabass 0.3.1

**Comment by milikhin** [comment]
Thank you! That seems to be a bug in editor's config in Seabass.

**Comment by milikhin** [comment]
Release schedule:

- ubports-seabass: v0.1.2
- harbour-seabass: v0.4.0
