### ISSUE TITLE
Remember last location when using Open file… dialogue

### ISSUE THREAD

**Issue by Pohli** [milikhin/seabass2#31]
See title. Maybe make it optional.

Jolla Phone with SFOS 3.0.1.11 and Seabass 0.3.1

**Comment by Danfro** [comment]
For UT this could maybe done by using `Settings`. Have on setting to store the last path when opening a file e.g. like `lastFolder = filepath` and then use this setting as default path when opening the file dialog.

Maybe it would need another bool setting for the user to decide if he wishes to use the last folder or the default folder (=home).

I have got no idea if this would work for SFOS too.

**Comment by milikhin** [comment]
No problems for UT here.

On SFOS on the other hand, a standard [FilePicker](https://sailfishos.org/develop/docs/sailfish-components-pickers/qml-sailfish-pickers-filepickerpage.html/) component is used to open files.
There seems to be no way to set initial directory for this component, and I don't want to re-implement file picker myself :-)

So, pull requests with a custom file picker are welcome to resolve the issue.
Python backend to read directories and FileList's model from UT version could be reused for SFOS to provide "tree" view.
