### ISSUE TITLE
Swipe to scroll changes cursor position

### ISSUE THREAD

**Issue by Pohli** [milikhin/seabass2#33]
Vertical scrolling by swiping up and down always changes the cursor position and brings up the virtual keyboard, too (if in edit mode).

Jolla Phone with SFOS 3.0.1.11 and Seabass 0.3.1

**Comment by milikhin** [comment]
Thank you!
That one, I think, is a "won't fix".

The WebView component provided by Sailfish OS (QtWebKit 3.0) is very outdated and seems to be the reason of the issue. There is no such problem in UBports app.
The issue should be gone when/if webview component in Sailfish SDK is updated.

**Comment by milikhin** [comment]
Such scrolling behaviour is the reason why "Readonly" mode has been introduced to make scrolling a little bit better :-)

**Comment by milikhin** [comment]
I won't fix the issue, but if anyone would like to work on it, pull requests are welcome!
