### ISSUE TITLE
Word wrapping: some text still in invisible area

### ISSUE THREAD

**Issue by Pohli** [milikhin/seabass2#34]
Although automatic word wrapping generally works the rightmost word is partially outside the visible area and when navigating to that invisible part (with cursor buttons) to write some additional characters I have to manually scroll to the right to see what I'm typing.

Jolla Phone with SFOS 3.0.1.11 and Seabass 0.3.1

**Comment by milikhin** [comment]
I can't reproduce the issue on Sailfish OS emulator.
Does it happen for every text file you open or there is something special about files with incorrect behaviour?

**Comment by Pohli** [comment]
It seems to be with every text file. What I've just noticed is that the width of the hidden area is the same like the width of the line number bar. That means if I scroll to the very right the line number bar is exactly hidden and I can see the complete text.

**Comment by milikhin** [comment]
Hm, for now I can't reproduce the issue. Could you please try current build: [seabass-master.zip](https://github.com/milikhin/seabass2/files/4707501/seabass-master.zip). Does the bug still there?

**Comment by Pohli** [comment]
I see no difference in behaviour. But now I noticed something else which may lead to a solution: After freshly starting Seabass and loading a text file there is no hidden area and no need to scroll horizontal. But as soon as I set the cursor somewhere with a tap and the virtual keyboard appears the visible text area and the line number bar zoom a bit in so that the invisible area emerges on the right. And the app stays in that zoom level after switching Read only mode several times and even after opening another text file. Only a restart of the app seems to reset the view.

**Comment by milikhin** [comment]
Thank you very much!
Could you please also have a look if changing device orientation helps to reset zoom to normal level?

**Comment by Pohli** [comment]
No, device orientation doesn't reset zoom level.

**Comment by milikhin** [comment]
I don't. My Xperia X is flashed with UBports for now :-)
But it didn't have scaling problems when I tested v0.3.1 release.

Emulator v3.0.1.11 is also unable to reproduce the issue.
Could you please try another build: [seabass-master.zip](https://github.com/milikhin/seabass2/files/4707656/seabass-master.zip)

**Comment by milikhin** [comment]
Should look similar to the picture below. There also should be empty space on the right side of the editor.

![issue](https://user-images.githubusercontent.com/13817735/83352797-64287f00-a378-11ea-8fa7-82d4e2d7aad1.png)

**Comment by Pohli** [comment]
Just that you don't misunderstand: What I wrote in the comment before my last comment applies to the official 0.3.1 version, too.
But now I found one difference: in the official 0.3.1 if I set the cursor for editing the first time the text will be zoomed in. In the two builds you linked here it won't zoom in at first edit most of the times but will zoom in after closing virtual keyboard and setting cursor again for editing.

If not zoomed in it looks almost like in your screenshot except that the white space on the right is not so large but that maybe could be caused by your example wrapping a longer word. I also got this thin light blue column at the right edge but only in latest build.

Another thing I noticed in every version is if the text is zoomed in I can peek into the area beyond the left and right edge but nothing to see there.

**Comment by milikhin** [comment]
Thank you for the feedback!
That seems to be quite an interesting issue :)
I still can't reproduce it, but I'll return to the issue when will be preparing v0.4.0 release and testing on a real device.

Just to be sure, you haven't manually installed any patches for the stock SFOS webview?
Like this one: https://openrepos.net/content/llelectronicsdev/qtwebkit-5212-dev

> I also got this thin light blue column at the right edge but only in latest build

Is this light blue column visible only when the app is scrolled to the right edge or is visible always regardless of zoom and scroll?

**Comment by Pohli** [comment]
No patches.
The column is always visible regardless of zoom level and scroll position.

**Comment by milikhin** [comment]
Thank you! This is very helpful!
Finally, it seems I've found a way to reproduce the behaviour you describe.
I'll add the issue to v0.4.0 milestone.

Technical information.
SFOS for some reason ignores `user-scalable=no` viewport option, so the current approach with `width=device-width, user-scalable=no` doesn't work reliably. Setting `initial-scale`/`maximum-scale` seems to work better.

**Comment by Pohli** [comment]
Glad to help and don't hesitate to upload another build for testing if needed. :-)

**Comment by milikhin** [comment]
Could you please try this build: [seabass-master-device-scale.zip](https://github.com/milikhin/seabass2/files/4716325/seabass-master-device-scale.zip)?

**Comment by Pohli** [comment]
Had a glance and it seems to be fixed. :-)

**Comment by milikhin** [comment]
Thank you very much for your help!

**Comment by Pohli** [comment]
You're welcome!
