### ISSUE TITLE
Enable automatic word suggestions in virtual keyboard

### ISSUE THREAD

**Issue by Pohli** [milikhin/seabass2#35]
See title.

Jolla Phone with SFOS 3.0.1.11 and Seabass 0.3.1

**Comment by Pohli** [comment]
I requested the same feature in another project. Maybe you can get an idea from there.
https://github.com/Wunderfitz/harbour-wunderfitz/issues/28

**Comment by milikhin** [comment]
Thank you for the issue.
I won't fix it myself because it requires too much investigation and possibly modifying some inner magic of the Ace Editor to make it compatible with SFOS virtual keyboard.

On the bright side, the next release will probable include code autocompletion.

**Comment by milikhin** [comment]
I think 'wontfix' suits better here for now due to the reasons above.
If anyone would like to work on the issue feel free to reopen it!
