### ISSUE TITLE
Add an indicator for unsaved changes

### ISSUE THREAD

**Issue by Pohli** [milikhin/seabass2#38]
My suggestion is to add the file name and maybe the whole path into some hidden area (e.g. pulley menu) and mark that there are unsaved changes with an asterisk. Additionally indicate that there are saved or unsaved changes directly in the main view, for example with light colours (e.g. green and red) in the background of text area or of the line number bar.

Jolla Phone with SFOS 3.0.1.11 and Seabass 0.3.1

**Comment by milikhin** [comment]
Blocked by #25

**Comment by milikhin** [comment]
Has been implemented in recent releases
