### ISSUE TITLE
Add fast scroll buttons

### ISSUE THREAD

**Issue by Pohli** [milikhin/seabass2#41]
Many SFOS apps have them and they would be very useful for long text files in Seabass.

Jolla Phone with SFOS 3.0.1.11 and Seabass 0.3.1

**Comment by milikhin** [comment]
QuickScroll relies heavily on SFOS native scroll capabilities.
Seabass doesn't use native SFOS scroll for Editor component (instead virtual scroll is implemented by Ace editor).

Resolving with `wontfix` as manual implementation of quick scroll would require too much work.
Long press on Up/Down navigation buttons is implemented as a workaround.

**Comment by Pohli** [comment]
Thanks for the hint to the workaround. I haven’t known before.

And yes I know this is 4 years old now. ☺
