### ISSUE TITLE
Setting cursor sometimes doesn't call virtual keyboard

### ISSUE THREAD

**Issue by Pohli** [milikhin/seabass2#50]
This issue happens approximately in 50 % of all attempts to set the cursor by tapping into the lower part of a text file. Either the virtual keyboard doesn't appear at all or it closes just after appearing. The only pattern I could make out is that it only happens tapping in that area that would be covered by the virtual keyboard.

Jolla Phone with SFOS 3.0.1.11 and Seabass 0.5.0

**Comment by milikhin** [comment]
Thank you for the issue!
I can reproduce it.

**Comment by milikhin** [comment]
Could you please try this build?
The keyboard should be automatically re-opened if it closes after appearing.

[harbour-seabass-0.5.1-1.zip](https://github.com/milikhin/seabass2/files/4838127/harbour-seabass-0.5.1-1.zip)

**Comment by Pohli** [comment]
I tested setting the cursor in 0.5.0 and 0.5.1 and case #1 (vk doesn't appear at all) didn't occur but I'm sure it sometimes does when using Seabass normally (not testing).
Case #2 (vk closes just after appearing) is fixed and even better than I thought when I read your comment cause the vk reappears very quickly. So it's not ideal, still a workaround but definitely not so annoying any more.
But now in 0.5.1 all the tool bar buttons don't work any more!

**Comment by milikhin** [comment]
Thank you very much!
Could you please try this build: [harbour-seabass-0.5.1-2.zip](https://github.com/milikhin/seabass2/files/4841840/harbour-seabass-0.5.1-2.zip)

It should have working tool bar and #32 (copying to clipboard) fixed!

**Comment by Pohli** [comment]
File name inside 0.5.1-2.zip is still harbour-seabass-0.5.1-1.noarch.rpm but a quick test shows that the tool bar works again.
And copy to clipboard also works in edit mode. In Read only mode text is selectable but not copied to clipboard.

**Comment by milikhin** [comment]
Thank you very much, this is very helpful!
