### ISSUE TITLE
Word completion window doesn't close after activating Read only mode

### ISSUE THREAD

**Issue by Pohli** [milikhin/seabass2#88]
**Describe the bug**
Word completion window doesn't close after activating Read only mode.

**To Reproduce**
1. Write some words which are already stored for the autocompletion feature.
2. While typing the last word, which must have been also stored before, don't use word completion (and if necessary stop typing in the middle of the word) to keep autocompletion window open.
3. Switch to Read only mode.
4. Autocompletion window is still there.

**Expected behavior**
Autocompletion window should disappear cause it's useless in Read only mode.

**Screenshots**
If necessary please let me know.

**Smartphone:**
 - Device: Jolla Phone
 - OS version: Sailfish OS 3.0.1.11
 - App version: 0.5.1

**Additional context**

**Comment by milikhin** [comment]
Thank you for the bug report!
