### ISSUE TITLE
implement option to set text size

### ISSUE THREAD

**Issue by Danfro** [milikhin/seabass2#92]
The eyesight of people is very different. Currently the text is rather small. That is great to fit more context on one page, but it may be hard to read for some people.

I think it would be good to have a "set text size" option as a settings. I would guess the simplest way might be a value to set for the text size. Another option might be a pinch-to-zoom (in/out).

Nothing major, just a suggestion.

**Comment by milikhin** [comment]
Thank you!
The issue is tracked in #13.
