### ISSUE TITLE
Scaling is big on external displays

### ISSUE THREAD

**Issue by kugiigi** [milikhin/seabass2#99]
**Describe the bug**
The scaling on external displays are always big and does not follow the current scaling of other apps or the system.

**To Reproduce**
1. Connect a device to a monitor (i.e. Nexus 5)
2. Open the app.
3. While in windowed mode, try dragging the app to the left most part of the screen to check if the scaling will be changed.
This is just to check if the current bug of system-wide app scaling is affecting the app.

**Expected behavior**
The app should be scaled according the system and other apps.

**Screenshots**
![screenshot20201103_224224185](https://user-images.githubusercontent.com/29456786/98383914-64c2f100-204d-11eb-8ace-5f3227e55dd4.png)

**Smartphone (please complete the following information):**
 - Device: Nexus 5
 - OS version: Ubuntu Touch OTA-13
 - App version: 0.11.0

**Additional context**
Some other apps like Authenticator NG has the same issue. My guess is that this is because the app does not use autoscaling for qqc2.

**Comment by milikhin** [comment]
Thank you very much for the bug report!

I've checked the code and I'm pretty sure that the Seabass doesn't set/alter any scaling-related parameters. My guess was that autoscaling would just work, but it seems that the app need to handle scaling somehow.

By the way, any chance you know how to set proper scaling for qqc2 apps in UT? :-)

**Comment by kugiigi** [comment]
You can set `Qt::AA_EnableHighDpiScaling` similar here.
https://github.com/kugiigi/pesbuk-app/blob/master/pesbuk/main.cpp

You can try this but it's possible that it will affect the scaling on the pinephone because there's an issue with qqc2 scaling there.
I can test it out if you want and see. I guess pinephone is more important than external display for now :)

**Comment by milikhin** [comment]
Thank you very much!
I've tried applying `QT_AUTO_SCREEN_SCALE_FACTOR=1` as it seems to be an equivalent for the `Qt::AA_EnableHighDpiScaling` and is available for me within a QML app without C++.

Could you please try the build: 
[seabass2-master-13-11T21-40.zip](https://github.com/milikhin/seabass2/files/5538980/seabass2-master-13-11T21-40.zip)

**Comment by milikhin** [comment]
[seabass-issue99-2020_11_15T21_15.zip](https://github.com/milikhin/seabass2/files/5542947/seabass-issue99-2020_11_15T21_15.zip)

**Comment by kugiigi** [comment]
It looks good now. Awesome and even on the pinephone the scaling is fine.
Did you updated the link for the file though? I'm not sure which version I tested.
![screenshot20201116_000625511](https://user-images.githubusercontent.com/29456786/99254945-76598500-2813-11eb-9646-d95b274b8a80.png)

**Comment by milikhin** [comment]
Thank you very much!

> Did you updated the link for the file though?
Yes, but it doesn't matter which version you've tried: the scaling remain unchanged, I've only removed a few unnecessary console.log calls and maybe added a few minor fixes here and there in the updated link :-)
